services:
  python:
    build: .
    container_name: stock-python
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: python Producer/main.py

  kafka:
    image: apache/kafka:3.7.0
    container_name: stock-kafka
    ports:
      - "9092:9092"

  spark:
    image: apache/spark:3.5.1
    container_name: stock-spark
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: stock-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stock_market
    ports:
      - "5432:5432"